# Common properties
spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Vola API configuration
vola.api.base-url=https://42cwka3n4ifcp7ufheyrpmph240iuaxo.lambda-url.eu-west-3.on.aws